version: '3.8'

services:
  api:
    build:
      context: ./Talabat.Demo.Solution
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db_default
      - db_identity
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db_default;Database=MainDb;User Id=sa;Password=YourStrong@Password1;
      - ConnectionStrings__IdentityConnection=Server=db_identity;Database=IdentityDb;User Id=sa;Password=YourStrong@Password2;
      - ConnectionStrings__Redis=redis:6379

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api

  db_default:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db_default
    environment:
      SA_PASSWORD: "YourStrong@Password1"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - db_default_data:/var/opt/mssql

  db_identity:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db_identity
    environment:
      SA_PASSWORD: "YourStrong@Password2"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    volumes:
      - db_identity_data:/var/opt/mssql

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  db_default_data:
  db_identity_data: